version: "3.8"

services:
  server:
    build:
      context: ./apps/server
    ports:
      - "3001:3001"
    env_file:
      - ./apps/server/.env
    restart: unless-stopped

  client:
    build:
      context: ./apps/client
    ports:
      - "80:80"
    depends_on:
      - server
