version: "3.8"

services:
  server:
    build:
      context: ./apps/server
    expose:
      - 3000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=3000
#    ports:
#      - "3010"
    ports:
      - "3000:3000"
      - "9229:9229" # For debugging
#    labels:
#      - "coolify.proxy=true"
#      - "coolify.domain=ama.garzn.com"
#      - "coolify.port=3010"
    env_file:
      - ./apps/server/.env
    restart: unless-stopped

  client:
    build:
      context: ./apps/client
    expose:
      - 80
#    ports:
#      - "81:80"  # Host:Container
    depends_on:
      - server
