version: "3.8"

services:
  server:
    build:
      context: ./apps/server
#    ports:
#      - "3010:3010"  # Host:Container
#    environment:
#      - PORT=3010
#    labels:
#      - "coolify.proxy=true"
#      - "coolify.domain=ama.garzn.com"
#      - "coolify.port=3010"
    env_file:
      - ./apps/server/.env
    restart: unless-stopped

  client:
    build:
      context: ./apps/client
    ports:
      - "81:80"  # Host:Container
    depends_on:
      - server
