version: "3.8"

services:
  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
#    expose:
#      - 3001
#    environment:
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
#      - PORT=3001
#    ports:
#      - "3001:3001"
#      - "9229:9229" # For debugging
    env_file:
      - ./apps/server/.env
    restart: unless-stopped

  client:
    build:
      context: ./apps/client
    expose:
      - 80
#    ports:
#      - "81:80"  # Host:Container
    depends_on:
      - server
