version: "3.8"

services:
  server:
    build:
      context: ./apps/server
    ports:
      - "3010:3010"  # Host:Container
    env_file:
      - ./apps/server/.env
    restart: unless-stopped

  client:
    build:
      context: ./apps/client
    ports:
      - "81:80"  # Host:Container
    depends_on:
      - server
